Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "localhost:3000"
  copyright: Copyright (C) 2013 Owl All Rights Reserved.
  title: blog title
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  port: 4321
  approot: "http://www.example.com"
  <<: *defaults
